server.port=8080

# MySQL Database Connection Configurations
spring.datasource.url=jdbc:mysql://localhost:3306/notes_app?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password123

# Tells Spring Boot to validate against the perfect tables you just built in Workbench
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Log SQL queries to console to monitor requests
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=MySuperSecretKeyForNotesAppInternshipAssignmentWhichNeedsToBeVeryLong
jwt.expiration=86400000