server.port=${PORT:8080}

# Cloud Database URL (Injected by Render)
spring.datasource.url=${DATABASE_URL}

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Key
jwt.secret=${JWT_SECRET:MySuperSecretKeyForNotesAppInternshipAssignmentWhichNeedsToBeVeryLong}
jwt.expiration=86400000